#spring.application.name=demo

spring:
  application:
    name: demo
  server:
    port: 8080
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
  datasource:
    url: jdbc:mysql://localhost:3306/PracticeDataBase
    username: root
    password: WXYkl040911!!
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mappers/*.xml
