#spring.application.name=demo

server:
  port: 8080

spring:
  application:
    name: Student-Management-System
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
  datasource:
    url: jdbc:mysql://localhost:3307/PracticeDataBase
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  aes:
    secret_key: ${AES_SECRET_KEY}
mybatis:
  mapper-locations: classpath:mappers/*.xml
